name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches: ["main"]  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out code
      - uses: actions/checkout@v4

      # Step 2: Install dependencies (if needed)
      - name: Install dependencies
        run: npm install

      # Step 3: Build frontend (adjust for your framework)
      - name: Build
        run: npm run build  # Assumes your `package.json` has a "build" script

      # Step 4: Deploy to Azure Static Web Apps
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"          # Root of your repo (where source files live)
          output_location: "dist"    # Folder with built files (e.g., Vite/Svelte/CRA uses "dist")
          skip_app_build: true      # Set to `false` if Azure should run `npm build`
